config/routes.rb
Rails.application.routes.draw do 
  devise_for :users
  #get 'home/index'
  #get 'users/index'
  resources :users, only: [:index, :edit, :update, :destroy] do 
    #collection do
      post 'import', on: :collection
    #end
  end

  root to: "users#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/generate_Csv.rb
# models/concerns/generate_csv.rb
module GenerateCsv
    extend ActiveSupport::Concern
  
    class_methods do
      def generate_csv(fields)
        CSV.generate(headers: true) do |csv|
          # Header
          csv << fields
          # Body
          all.each do |record|
            csv << record.attributes.values_at(*fields)
          end
        end
      end
    end
end

app/models/user.rb
require 'csv'
class User < ApplicationRecord
  include GenerateCsv
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :firstname, :lastname, presence: true

  # Add user's role enum
  enum role: { admin: "admin", manager: "manager", user: "user"}
  # Add Default role value
  attribute :role, :string, default: "user"

  # Add csv file informatin into database
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      users_hash = row.to_hash      
      find_or_create_by!(email: users_hash['email']) do |u|
        u.password = "password123"
        u.firstname = users_hash["firstname"]
        u.lastname = users_hash["lastname"]
        u.role = users_hash["role"]
        u.address = users_hash["address"]
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    protect_from_forgery with: :exception
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:firstname, :lastname, :address, :contatno, :email, :password, :role) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:firstname, :lastname, :address, :contatno, :email, :role, :password, :current_password) }
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index   
    # pagination code, items: 'record count per page'
    @pagy, @users = pagy(get_users, items: 2)

    respond_to do |format|
      format.html{}
      format.csv { send_data get_users.generate_csv(csv_attr), filename: "users-#{Time.now}.csv" }
      format.json { render json: @users, status: :ok }
    end
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        produce_message # kafka code for produce code
        format.html { redirect_to users_url , notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # DELETE /users/import
  def import
    current_user_count = user_count
    begin
      @user_cnt = User.import(params[:my_csv_file])
      current_user_count = user_count - current_user_count
    rescue Exception => e
      redirect_to root_url, alert: "Import user failed, #{e.message}"
    else
      redirect_to root_url, notice: "#{current_user_count} Users imported."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Get users list based on Role
    def get_users
      objUser = User
      users_filter = objUser.all if current_user.admin? || current_user.id == 1
      users_filter = objUser.where("role = ? or id = ?", :user, current_user.id) if current_user.manager?
      users_filter = objUser.where(id: current_user.id)  if current_user.user?
      return users_filter
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:firstname,:lastname,:contatno,:address, :role, :email)
    end

    def user_count
      User.count
    end

    def csv_attr
      ['email','firstname', 'lastname', 'address', 'role']
    end


    def produce_message
        $kafka_producer.produce(@user.to_json, topic: "user_update", partition_key: @user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="text-muted">© 2021 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
</footer>  

app/views/layouts/_header.html.erb
<header class="p-3 bg-dark text-white mb-2">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= link_to "Home", root_path, class: "nav-link px-2 text-secondary" %></li>
        </ul>

        <div class="text-end">
          <% if user_signed_in? %>
            <%= link_to('My Profile', edit_user_registration_path, class: "btn btn-outline-light me-2") %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "btn btn-success") %>
          <% end %>
          
        </div>
      </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Userdemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    <div class="container">
      <% if user_signed_in? %>
        <%= render "layouts/header" %>
      <% end %>
      
      <% if notice.present? %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>

      <% if alert.present? %>
        <div class="alert alert-warning" role="alert"><%= alert %></div>
      <% end %>

      <%= yield %>

      <% if user_signed_in? %>
        <%= render "layouts/footer" %>
      <% end %>
    </div>  
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<section class="vh-100 bg-image" style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.jpg');">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-sm-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">              
              <h2  class="text-uppercase text-center mb-5">Edit </h2>              
                <div class="row">
                  <div class="col-md-6 mb-4 pb-2">
                    <div class="form-outline">
                      <%= f.text_field :firstname, autofocus: true, placeholder: "First Name", class:"form-control form-control-sm" %>                                        
                    </div>
                  </div>                
                  <div class="col-md-6 mb-4 pb-2">
                    <div class="form-outline">
                      <%= f.text_field :lastname, autofocus: true, placeholder: "Last Name", class:"form-control form-control-sm" %>
                    </div>
                  </div>
                </div>

                <div class="form-outline mb-4">
                  <%= f.text_field :address, autofocus: true, placeholder: "Address", class:"form-control form-control-sm" %>
                </div>

                <div class="form-outline mb-4">
                  <%= f.text_field :contatno, autofocus: true, placeholder: "Contact No", class:"form-control form-control-sm" %>
                </div>

                <div class="form-outline mb-4">
                  <%= f.email_field :email, autofocus: true, placeholder: "Email Id", class:"form-control form-control-sm" %>
                </div>
                
                <div class="mb-4">
                  <% if current_user.admin? && !user.admin? %>
                    <%= f.select :role, User.roles, {},class:"form-select form-select-sm mb-3" %>
                  <% else %>
                  <strong>Role: <%=user.role.upcase %></strong>
                  <% end %>
                </div>

                <div class="d-flex justify-content-center">
                  <%= f.submit "Update", class: "btn btn-success btn-block btn-sm gradient-custom-4 text-body" %>                  
                </div>
                <%= link_to "Back", root_path %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div class="float-end mt-4 mb-4">
  <%= form_tag import_users_path, multipart: true, class: 'row g-3 needs-validation' do %> 
    <div class="col-auto">
      <%= file_field_tag :my_csv_file, class: 'form-control', required: "required", accept: ".csv" %>       
    </div>
    <div class="col-auto">
      <%= submit_tag "Import CSV", class: 'btn btn-info' %>
      <%= link_to "Export CSV", users_path(format: "csv"), class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

<table class="table mt-4 pt-2">
  <thead class="table-dark">
    <tr>
        <td>First Name<td>
        <td>Last Name<td>
        <td>Role<td>
        <td>Email<td>
        <td>Contact no<td>
        <td>Address<td>
        <td>Edit<td>
        <td>Delete<td>
    </tr>
  </thead>  
  
  <tbody>
    <% @users.each do |user| %>
      <tr>
          <td><%=user.firstname%><td>
          <td><%=user.lastname%><td>
          <td><%=user.role.upcase%><td>
          <td><%=user.email%><td>
          <td><%=user.contatno.to_i%><td>
          <td><%=user.address%><td>
          <td><%=link_to "Edit", edit_user_path(user.id), class: "btn btn-warning"%><td>
          <td><%=link_to "Delete", user_path(user.id), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" if current_user.admin? && !user.admin? %><td>
      </tr>
    <% end %>    
  </tbody>  
</table>

<!-- Pagination code -->
<%== pagy_bootstrap_nav(@pagy) %>